-- Seed quiz questions for HTML Basics Quiz
INSERT INTO public.quiz_questions (quiz_id, question_text, options, correct_answer, explanation) VALUES ((SELECT id FROM public.quizzes WHERE title = 'HTML Basics Quiz' LIMIT 1), 'Apa singkatan dari HTML?', '{"A": "HyperText Markup Language", "B": "HighText Machine Language", "C": "HyperText and links Markup Language", "D": "HomeTool Markup Language"}', 'A', 'HTML adalah singkatan dari HyperText Markup Language, bahasa markup standar untuk membuat halaman web.');
INSERT INTO public.quiz_questions (quiz_id, question_text, options, correct_answer, explanation) VALUES ((SELECT id FROM public.quizzes WHERE title = 'HTML Basics Quiz' LIMIT 1), 'Tag HTML mana yang digunakan untuk membuat heading utama?', '{"A": "<head>", "B": "<h1>", "C": "<header>", "D": "<heading>"}', 'B', 'Tag <h1> digunakan untuk heading utama, diikuti oleh <h2>, <h3>, dll untuk sub-heading.');
INSERT INTO public.quiz_questions (quiz_id, question_text, options, correct_answer, explanation) VALUES ((SELECT id FROM public.quizzes WHERE title = 'HTML Basics Quiz' LIMIT 1), 'Tag HTML mana yang digunakan untuk membuat paragraf?', '{"A": "<p>", "B": "<para>", "C": "<paragraph>", "D": "<text>"}', 'A', 'Tag <p> digunakan untuk membuat paragraf teks.');
INSERT INTO public.quiz_questions (quiz_id, question_text, options, correct_answer, explanation) VALUES ((SELECT id FROM public.quizzes WHERE title = 'HTML Basics Quiz' LIMIT 1), 'Atribut HTML mana yang digunakan untuk memberikan ID unik pada elemen?', '{"A": "class", "B": "id", "C": "name", "D": "unique"}', 'B', 'Atribut id digunakan untuk memberikan identifikasi unik pada elemen HTML.');
INSERT INTO public.quiz_questions (quiz_id, question_text, options, correct_answer, explanation) VALUES ((SELECT id FROM public.quizzes WHERE title = 'HTML Basics Quiz' LIMIT 1), 'Tag HTML mana yang digunakan untuk membuat link?', '{"A": "<link>", "B": "<a>", "C": "<href>", "D": "<url>"}', 'B', 'Tag <a> (anchor) digunakan untuk membuat hyperlink ke halaman lain atau bagian dalam halaman.');
INSERT INTO public.quiz_questions (quiz_id, question_text, options, correct_answer, explanation) VALUES ((SELECT id FROM public.quizzes WHERE title = 'HTML Basics Quiz' LIMIT 1), 'Tag HTML mana yang digunakan untuk menampilkan gambar?', '{"A": "<image>", "B": "<img>", "C": "<picture>", "D": "<photo>"}', 'B', 'Tag <img> digunakan untuk menampilkan gambar dengan atribut src untuk menentukan lokasi gambar.');
INSERT INTO public.quiz_questions (quiz_id, question_text, options, correct_answer, explanation) VALUES ((SELECT id FROM public.quizzes WHERE title = 'HTML Basics Quiz' LIMIT 1), 'Apa fungsi dari tag <br>?', '{"A": "Membuat baris baru", "B": "Membuat paragraf baru", "C": "Membuat heading", "D": "Membuat list"}', 'A', 'Tag <br> digunakan untuk membuat line break atau baris baru.');
INSERT INTO public.quiz_questions (quiz_id, question_text, options, correct_answer, explanation) VALUES ((SELECT id FROM public.quizzes WHERE title = 'HTML Basics Quiz' LIMIT 1), 'Tag HTML mana yang digunakan untuk membuat list tidak berurutan?', '{"A": "<list>", "B": "<ul>", "C": "<ol>", "D": "<li>"}', 'B', 'Tag <ul> (unordered list) digunakan untuk membuat list dengan bullet points.');
INSERT INTO public.quiz_questions (quiz_id, question_text, options, correct_answer, explanation) VALUES ((SELECT id FROM public.quizzes WHERE title = 'HTML Basics Quiz' LIMIT 1), 'Atribut HTML mana yang digunakan untuk memberikan style CSS inline?', '{"A": "style", "B": "css", "C": "class", "D": "inline"}', 'A', 'Atribut style digunakan untuk menambahkan CSS inline langsung pada elemen HTML.');
INSERT INTO public.quiz_questions (quiz_id, question_text, options, correct_answer, explanation) VALUES ((SELECT id FROM public.quizzes WHERE title = 'HTML Basics Quiz' LIMIT 1), 'Tag HTML mana yang digunakan untuk membuat tabel?', '{"A": "<table>", "B": "<tab>", "C": "<grid>", "D": "<data>"}', 'A', 'Tag <table> digunakan sebagai container untuk membuat tabel HTML.');

-- Seed quiz questions for JavaScript Quiz
INSERT INTO public.quiz_questions (quiz_id, question_text, options, correct_answer, explanation) VALUES ((SELECT id FROM public.quizzes WHERE title = 'JavaScript Quiz' LIMIT 1), 'Apa tipe data yang digunakan untuk menyimpan teks di JavaScript?', '{"A": "string", "B": "text", "C": "char", "D": "word"}', 'A', 'String adalah tipe data yang digunakan untuk menyimpan teks atau karakter di JavaScript.');
INSERT INTO public.quiz_questions (quiz_id, question_text, options, correct_answer, explanation) VALUES ((SELECT id FROM public.quizzes WHERE title = 'JavaScript Quiz' LIMIT 1), 'Operator apa yang digunakan untuk membandingkan nilai dan tipe data?', '{"A": "==", "B": "===", "C": "=", "D": "!="}', 'B', 'Operator === (strict equality) membandingkan baik nilai maupun tipe data.');
INSERT INTO public.quiz_questions (quiz_id, question_text, options, correct_answer, explanation) VALUES ((SELECT id FROM public.quizzes WHERE title = 'JavaScript Quiz' LIMIT 1), 'Fungsi JavaScript mana yang digunakan untuk menampilkan pesan di console?', '{"A": "alert()", "B": "print()", "C": "console.log()", "D": "display()"}', 'C', 'console.log() digunakan untuk menampilkan pesan di console browser untuk debugging.');
INSERT INTO public.quiz_questions (quiz_id, question_text, options, correct_answer, explanation) VALUES ((SELECT id FROM public.quizzes WHERE title = 'JavaScript Quiz' LIMIT 1), 'Cara mana yang benar untuk mendeklarasikan variabel di JavaScript modern?', '{"A": "var myVar;", "B": "let myVar;", "C": "const myVar;", "D": "Semua benar"}', 'D', 'JavaScript modern menggunakan let dan const untuk mendeklarasi variabel, meskipun var masih didukung.');
INSERT INTO public.quiz_questions (quiz_id, question_text, options, correct_answer, explanation) VALUES ((SELECT id FROM public.quizzes WHERE title = 'JavaScript Quiz' LIMIT 1), 'Apa hasil dari 5 + "5" di JavaScript?', '{"A": "10", "B": "55", "C": "Error", "D": "undefined"}', 'B', 'JavaScript melakukan type coercion, mengubah angka 5 menjadi string sehingga hasilnya adalah "55".');
INSERT INTO public.quiz_questions (quiz_id, question_text, options, correct_answer, explanation) VALUES ((SELECT id FROM public.quizzes WHERE title = 'JavaScript Quiz' LIMIT 1), 'Metode array mana yang digunakan untuk menambahkan elemen di akhir array?', '{"A": "push()", "B": "add()", "C": "append()", "D": "insert()"}', 'A', 'Metode push() menambahkan satu atau lebih elemen di akhir array dan mengembalikan panjang array baru.');
INSERT INTO public.quiz_questions (quiz_id, question_text, options, correct_answer, explanation) VALUES ((SELECT id FROM public.quizzes WHERE title = 'JavaScript Quiz' LIMIT 1), 'Struktur kontrol mana yang digunakan untuk mengeksekusi kode berulang?', '{"A": "if-else", "B": "switch", "C": "for", "D": "try-catch"}', 'C', 'Loop for digunakan untuk mengeksekusi blok kode berulang kali selama kondisi tertentu terpenuhi.');
INSERT INTO public.quiz_questions (quiz_id, question_text, options, correct_answer, explanation) VALUES ((SELECT id FROM public.quizzes WHERE title = 'JavaScript Quiz' LIMIT 1), 'Apa itu DOM dalam konteks JavaScript?', '{"A": "Document Object Model", "B": "Data Object Management", "C": "Dynamic Object Method", "D": "Display Object Model"}', 'A', 'DOM (Document Object Model) adalah representasi struktur HTML sebagai objek yang dapat dimanipulasi dengan JavaScript.');
INSERT INTO public.quiz_questions (quiz_id, question_text, options, correct_answer, explanation) VALUES ((SELECT id FROM public.quizzes WHERE title = 'JavaScript Quiz' LIMIT 1), 'Fungsi JavaScript mana yang digunakan untuk menunda eksekusi kode?', '{"A": "delay()", "B": "wait()", "C": "setTimeout()", "D": "pause()"}', 'C', 'setTimeout() menjadwalkan eksekusi fungsi setelah waktu tertentu dalam milidetik.');
INSERT INTO public.quiz_questions (quiz_id, question_text, options, correct_answer, explanation) VALUES ((SELECT id FROM public.quizzes WHERE title = 'JavaScript Quiz' LIMIT 1), 'Apa itu callback function di JavaScript?', '{"A": "Fungsi yang dipanggil kembali", "B": "Fungsi yang dipanggil sebagai argumen", "C": "Fungsi yang mengembalikan nilai", "D": "Fungsi yang tidak memiliki parameter"}', 'B', 'Callback function adalah fungsi yang diberikan sebagai argumen ke fungsi lain dan dipanggil ketika operasi selesai.');
INSERT INTO public.quiz_questions (quiz_id, question_text, options, correct_answer, explanation) VALUES ((SELECT id FROM public.quizzes WHERE title = 'JavaScript Quiz' LIMIT 1), 'Metode string mana yang digunakan untuk mengubah string menjadi huruf besar?', '{"A": "toUpper()", "B": "upperCase()", "C": "toUpperCase()", "D": "makeUpper()"}', 'C', 'Metode toUpperCase() mengubah semua karakter dalam string menjadi huruf besar.');
INSERT INTO public.quiz_questions (quiz_id, question_text, options, correct_answer, explanation) VALUES ((SELECT id FROM public.quizzes WHERE title = 'JavaScript Quiz' LIMIT 1), 'Operator apa yang digunakan untuk spread syntax di JavaScript?', '{"A": "...", "B": "***", "C": "&&&", "D": "|||"}', 'A', 'Operator spread (...) digunakan untuk menyebarkan elemen array atau properti objek.');
INSERT INTO public.quiz_questions (quiz_id, question_text, options, correct_answer, explanation) VALUES ((SELECT id FROM public.quizzes WHERE title = 'JavaScript Quiz' LIMIT 1), 'Apa itu Promise di JavaScript?', '{"A": "Janji untuk mengeksekusi kode", "B": "Objek yang mewakili penyelesaian operasi async", "C": "Fungsi yang mengembalikan nilai", "D": "Variabel global"}', 'B', 'Promise adalah objek yang mewakili penyelesaian (atau kegagalan) operasi asynchronous dan nilai yang dihasilkan.');
INSERT INTO public.quiz_questions (quiz_id, question_text, options, correct_answer, explanation) VALUES ((SELECT id FROM public.quizzes WHERE title = 'JavaScript Quiz' LIMIT 1), 'Sintaks mana yang benar untuk arrow function?', '{"A": "function() => {}", "B": "() => {}", "C": "=> () {}", "D": "function => () {}"}', 'B', 'Sintaks arrow function adalah () => {} untuk fungsi tanpa parameter.');
INSERT INTO public.quiz_questions (quiz_id, question_text, options, correct_answer, explanation) VALUES ((SELECT id FROM public.quizzes WHERE title = 'JavaScript Quiz' LIMIT 1), 'Apa itu hoisting di JavaScript?', '{"A": "Mengangkat variabel ke atas", "B": "Menurunkan variabel ke bawah", "C": "Menghapus variabel", "D": "Mengganti nama variabel"}', 'A', 'Hoisting adalah perilaku JavaScript di mana deklarasi variabel dan fungsi diangkat ke atas scope mereka sebelum eksekusi kode.');

-- Seed quiz questions for React Quiz
INSERT INTO public.quiz_questions (quiz_id, question_text, options, correct_answer, explanation) VALUES ((SELECT id FROM public.quizzes WHERE title = 'React Quiz' LIMIT 1), 'Apa itu React?', '{"A": "Database", "B": "JavaScript library untuk UI", "C": "CSS framework", "D": "Server"}', 'B', 'React adalah library JavaScript untuk membangun user interface yang interaktif dan efisien.');
INSERT INTO public.quiz_questions (quiz_id, question_text, options, correct_answer, explanation) VALUES ((SELECT id FROM public.quizzes WHERE title = 'React Quiz' LIMIT 1), 'Apa itu JSX?', '{"A": "JavaScript XML", "B": "Java Syntax Extension", "C": "JSON XML", "D": "JavaScript Extension"}', 'A', 'JSX adalah ekstensi sintaks untuk JavaScript yang memungkinkan penulisan HTML dalam kode React.');
INSERT INTO public.quiz_questions (quiz_id, question_text, options, correct_answer, explanation) VALUES ((SELECT id FROM public.quizzes WHERE title = 'React Quiz' LIMIT 1), 'Hook mana yang digunakan untuk state management di React?', '{"A": "useState", "B": "useEffect", "C": "useContext", "D": "useReducer"}', 'A', 'useState adalah hook fundamental untuk menambahkan state ke komponen fungsional.');
INSERT INTO public.quiz_questions (quiz_id, question_text, options, correct_answer, explanation) VALUES ((SELECT id FROM public.quizzes WHERE title = 'React Quiz' LIMIT 1), 'Apa itu props di React?', '{"A": "Properti komponen", "B": "Parameter yang diteruskan ke komponen", "C": "State internal komponen", "D": "Event handler"}', 'B', 'Props adalah parameter yang diteruskan dari komponen induk ke komponen anak.');
INSERT INTO public.quiz_questions (quiz_id, question_text, options, correct_answer, explanation) VALUES ((SELECT id FROM public.quizzes WHERE title = 'React Quiz' LIMIT 1), 'Hook mana yang digunakan untuk efek samping di React?', '{"A": "useState", "B": "useEffect", "C": "useMemo", "D": "useCallback"}', 'B', 'useEffect digunakan untuk menangani efek samping seperti fetching data, subscriptions, atau DOM manipulation.');
INSERT INTO public.quiz_questions (quiz_id, question_text, options, correct_answer, explanation) VALUES ((SELECT id FROM public.quizzes WHERE title = 'React Quiz' LIMIT 1), 'Apa itu Virtual DOM?', '{"A": "Copy dari real DOM", "B": "Representasi ringan dari UI di memori", "C": "Database virtual", "D": "DOM yang tidak terlihat"}', 'B', 'Virtual DOM adalah representasi ringan dari UI yang disimpan di memori dan disinkronkan dengan real DOM.');
INSERT INTO public.quiz_questions (quiz_id, question_text, options, correct_answer, explanation) VALUES ((SELECT id FROM public.quizzes WHERE title = 'React Quiz' LIMIT 1), 'Metode lifecycle mana yang dipanggil ketika komponen akan dihapus?', '{"A": "componentDidMount", "B": "componentDidUpdate", "C": "componentWillUnmount", "D": "render"}', 'C', 'componentWillUnmount dipanggil tepat sebelum komponen dihapus dari DOM.');
INSERT INTO public.quiz_questions (quiz_id, question_text, options, correct_answer, explanation) VALUES ((SELECT id FROM public.quizzes WHERE title = 'React Quiz' LIMIT 1), 'Apa itu key prop di React?', '{"A": "Password untuk komponen", "B": "Identifier unik untuk list items", "C": "CSS class", "D": "Event handler"}', 'B', 'Key prop membantu React mengidentifikasi item mana yang telah berubah, ditambahkan, atau dihapus dalam list.');
INSERT INTO public.quiz_questions (quiz_id, question_text, options, correct_answer, explanation) VALUES ((SELECT id FROM public.quizzes WHERE title = 'React Quiz' LIMIT 1), 'Hook mana yang digunakan untuk mengoptimalkan performa dengan memoization?', '{"A": "useState", "B": "useEffect", "C": "useMemo", "D": "useRef"}', 'C', 'useMemo mengembalikan nilai memoized dari komputasi yang mahal dan hanya menghitung ulang ketika dependencies berubah.');
INSERT INTO public.quiz_questions (quiz_id, question_text, options, correct_answer, explanation) VALUES ((SELECT id FROM public.quizzes WHERE title = 'React Quiz' LIMIT 1), 'Apa itu controlled component?', '{"A": "Komponen yang dikontrol oleh parent", "B": "Form element yang nilainya dikontrol oleh React state", "C": "Komponen yang tidak bisa diubah", "D": "Komponen dengan banyak props"}', 'B', 'Controlled component adalah form element di mana nilai dikontrol oleh state React.');
INSERT INTO public.quiz_questions (quiz_id, question_text, options, correct_answer, explanation) VALUES ((SELECT id FROM public.quizzes WHERE title = 'React Quiz' LIMIT 1), 'Apa fungsi dari useCallback hook?', '{"A": "Membuat state", "B": "Memoize fungsi", "C": "Menangani event", "D": "Mengambil data"}', 'B', 'useCallback mengembalikan versi memoized dari callback yang hanya berubah jika dependencies berubah.');
INSERT INTO public.quiz_questions (quiz_id, question_text, options, correct_answer, explanation) VALUES ((SELECT id FROM public.quizzes WHERE title = 'React Quiz' LIMIT 1), 'Apa itu React Fragment?', '{"A": "Potongan kode React", "B": "Wrapper yang tidak menambah elemen DOM", "C": "Error handling", "D": "State management"}', 'B', 'React Fragment memungkinkan mengelompokkan multiple elemen tanpa menambah node ekstra ke DOM.');

-- First, ensure quizzes exist (only insert if they don't already exist)
INSERT INTO public.quizzes (title, description, total_questions, passing_score, category)
SELECT 'Design Principles Quiz', 'Test your design principles knowledge', 20, 80, 'DKV'
WHERE NOT EXISTS (SELECT 1 FROM public.quizzes WHERE title = 'Design Principles Quiz');

INSERT INTO public.quizzes (title, description, total_questions, passing_score, category)
SELECT 'Computer Networking Quiz', 'Test your networking knowledge', 20, 80, 'TKJ'
WHERE NOT EXISTS (SELECT 1 FROM public.quizzes WHERE title = 'Computer Networking Quiz');

INSERT INTO public.quizzes (title, description, total_questions, passing_score, category)
SELECT 'Telecommunications Quiz', 'Test your telecommunications knowledge', 20, 80, 'TRANS'
WHERE NOT EXISTS (SELECT 1 FROM public.quizzes WHERE title = 'Telecommunications Quiz');

INSERT INTO public.quizzes (title, description, total_questions, passing_score, category)
SELECT 'Database Design Quiz', 'Test your database design knowledge', 20, 80, 'RPL'
WHERE NOT EXISTS (SELECT 1 FROM public.quizzes WHERE title = 'Database Design Quiz');

-- Seed quiz questions for Design Principles Quiz (DKV)
INSERT INTO public.quiz_questions (quiz_id, question_text, options, correct_answer, explanation) VALUES ((SELECT id FROM public.quizzes WHERE title = 'Design Principles Quiz' LIMIT 1), 'Apa yang dimaksud dengan desain grafis?', '{"A": "Seni memasak", "B": "Seni visual untuk menyampaikan pesan", "C": "Teknik programming", "D": "Analisis data"}', 'B', 'Desain grafis adalah seni dan praktik visual untuk menyampaikan ide dan pesan melalui gambar, teks, dan bentuk.');
INSERT INTO public.quiz_questions (quiz_id, question_text, options, correct_answer, explanation) VALUES ((SELECT id FROM public.quizzes WHERE title = 'Design Principles Quiz' LIMIT 1), 'Elemen dasar desain yang paling fundamental adalah?', '{"A": "Warna", "B": "Garis", "C": "Tekstur", "D": "Ruang"}', 'B', 'Garis adalah elemen paling dasar dalam desain, bisa lurus, lengkung, tebal, atau tipis.');
INSERT INTO public.quiz_questions (quiz_id, question_text, options, correct_answer, explanation) VALUES ((SELECT id FROM public.quizzes WHERE title = 'Design Principles Quiz' LIMIT 1), 'Prinsip desain yang menarik perhatian dengan perbedaan adalah?', '{"A": "Balance", "B": "Contrast", "C": "Emphasis", "D": "Movement"}', 'B', 'Contrast adalah prinsip desain yang menggunakan perbedaan untuk menarik perhatian dan membuat elemen menonjol.');
INSERT INTO public.quiz_questions (quiz_id, question_text, options, correct_answer, explanation) VALUES ((SELECT id FROM public.quizzes WHERE title = 'Design Principles Quiz' LIMIT 1), 'Warna primer dalam teori warna adalah?', '{"A": "Hijau, Orange, Ungu", "B": "Merah, Kuning, Biru", "C": "Hitam, Putih, Abu", "D": "Pink, Biru muda, Kuning"}', 'B', 'Warna primer adalah Merah, Kuning, dan Biru yang tidak bisa dibuat dari campuran warna lain.');
INSERT INTO public.quiz_questions (quiz_id, question_text, options, correct_answer, explanation) VALUES ((SELECT id FROM public.quizzes WHERE title = 'Design Principles Quiz' LIMIT 1), 'Font family yang cocok untuk heading adalah?', '{"A": "Sans-serif", "B": "Serif", "C": "Script", "D": "Display"}', 'D', 'Display fonts biasanya digunakan untuk heading karena memiliki karakter yang menarik dan mudah dibaca dalam ukuran besar.');
INSERT INTO public.quiz_questions (quiz_id, question_text, options, correct_answer, explanation) VALUES ((SELECT id FROM public.quizzes WHERE title = 'Design Principles Quiz' LIMIT 1), 'Rule of Thirds membagi area desain menjadi?', '{"A": "4 bagian", "B": "6 bagian", "C": "9 bagian", "D": "12 bagian"}', 'C', 'Rule of Thirds membagi area menjadi 9 bagian dengan 2 garis horizontal dan 2 garis vertikal.');
INSERT INTO public.quiz_questions (quiz_id, question_text, options, correct_answer, explanation) VALUES ((SELECT id FROM public.quizzes WHERE title = 'Design Principles Quiz' LIMIT 1), 'Software yang digunakan untuk editing foto profesional adalah?', '{"A": "Adobe Illustrator", "B": "Adobe Photoshop", "C": "Adobe InDesign", "D": "CorelDRAW"}', 'B', 'Adobe Photoshop adalah software utama untuk editing foto dan gambar raster.');
INSERT INTO public.quiz_questions (quiz_id, question_text, options, correct_answer, explanation) VALUES ((SELECT id FROM public.quizzes WHERE title = 'Design Principles Quiz' LIMIT 1), 'Jenis desain yang digunakan untuk identitas merek adalah?', '{"A": "Poster Design", "B": "Logo Design", "C": "Banner Design", "D": "Packaging Design"}', 'B', 'Logo design adalah desain yang digunakan untuk menciptakan identitas visual merek perusahaan.');
INSERT INTO public.quiz_questions (quiz_id, question_text, options, correct_answer, explanation) VALUES ((SELECT id FROM public.quizzes WHERE title = 'Design Principles Quiz' LIMIT 1), 'Tahap pertama dalam proses desain adalah?', '{"A": "Sketch", "B": "Brief", "C": "Digital Draft", "D": "Final"}', 'B', 'Brief adalah tahap pertama dimana desainer memahami kebutuhan dan requirement dari klien.');
INSERT INTO public.quiz_questions (quiz_id, question_text, options, correct_answer, explanation) VALUES ((SELECT id FROM public.quizzes WHERE title = 'Design Principles Quiz' LIMIT 1), 'Tren desain 2024 yang menekankan kesederhanaan adalah?', '{"A": "3D Design", "B": "Minimalism", "C": "Gradient", "D": "Typography"}', 'B', 'Minimalism adalah tren desain yang menekankan kesederhanaan namun tetap powerful dan efektif.');
INSERT INTO public.quiz_questions (quiz_id, question_text, options, correct_answer, explanation) VALUES ((SELECT id FROM public.quizzes WHERE title = 'Design Principles Quiz' LIMIT 1), 'Platform untuk mencari inspirasi desain adalah?', '{"A": "GitHub", "B": "Behance", "C": "Stack Overflow", "D": "Docker Hub"}', 'B', 'Behance adalah platform populer untuk mencari inspirasi dan showcase karya desain grafis.');
INSERT INTO public.quiz_questions (quiz_id, question_text, options, correct_answer, explanation) VALUES ((SELECT id FROM public.quizzes WHERE title = 'Design Principles Quiz' LIMIT 1), 'Soft skill yang penting untuk desainer grafis adalah?', '{"A": "Programming", "B": "Creativity", "C": "Data Analysis", "D": "Accounting"}', 'B', 'Creativity adalah soft skill utama yang dibutuhkan desainer grafis untuk menghasilkan ide-ide inovatif.');
INSERT INTO public.quiz_questions (quiz_id, question_text, options, correct_answer, explanation) VALUES ((SELECT id FROM public.quizzes WHERE title = 'Design Principles Quiz' LIMIT 1), 'Komponen utama dalam membangun portfolio desainer adalah?', '{"A": "Personal Website", "B": "Social Media Posts", "C": "Email Collection", "D": "Business Cards"}', 'A', 'Personal website adalah komponen utama portfolio untuk showcase karya desain secara profesional.');
INSERT INTO public.quiz_questions (quiz_id, question_text, options, correct_answer, explanation) VALUES ((SELECT id FROM public.quizzes WHERE title = 'Design Principles Quiz' LIMIT 1), 'Apa yang dimaksud dengan white space dalam desain?', '{"A": "Area berwarna putih", "B": "Ruang kosong yang strategis", "C": "Background transparan", "D": "Border putih"}', 'B', 'White space adalah ruang kosong yang sengaja dibiarkan kosong untuk meningkatkan readability dan estetika.');

-- Seed quiz questions for Computer Networking Quiz (TKJ)
INSERT INTO public.quiz_questions (quiz_id, question_text, options, correct_answer, explanation) VALUES ((SELECT id FROM public.quizzes WHERE title = 'Computer Networking Quiz' LIMIT 1), 'Apa yang dimaksud dengan jaringan komputer?', '{"A": "Sistem komputer tunggal", "B": "Kumpulan komputer yang terhubung", "C": "Software antivirus", "D": "Program office"}', 'B', 'Jaringan komputer adalah sistem yang menghubungkan komputer dan perangkat lain untuk berbagi sumber daya dan berkomunikasi.');
INSERT INTO public.quiz_questions (quiz_id, question_text, options, correct_answer, explanation) VALUES ((SELECT id FROM public.quizzes WHERE title = 'Computer Networking Quiz' LIMIT 1), 'Tipe jaringan berdasarkan jangkauan yang paling luas adalah?', '{"A": "PAN", "B": "LAN", "C": "MAN", "D": "WAN"}', 'D', 'WAN (Wide Area Network) memiliki jangkauan nasional atau global, seperti internet.');
INSERT INTO public.quiz_questions (quiz_id, question_text, options, correct_answer, explanation) VALUES ((SELECT id FROM public.quizzes WHERE title = 'Computer Networking Quiz' LIMIT 1), 'Topologi jaringan dimana semua perangkat terhubung ke satu kabel utama adalah?', '{"A": "Star", "B": "Ring", "C": "Bus", "D": "Mesh"}', 'C', 'Topologi bus menghubungkan semua perangkat ke satu kabel utama (backbone).');
INSERT INTO public.quiz_questions (quiz_id, question_text, options, correct_answer, explanation) VALUES ((SELECT id FROM public.quizzes WHERE title = 'Computer Networking Quiz' LIMIT 1), 'Layer dalam model OSI yang bertanggung jawab untuk routing adalah?', '{"A": "Physical", "B": "Data Link", "C": "Network", "D": "Transport"}', 'C', 'Layer Network (layer 3) bertanggung jawab untuk routing dan logical addressing seperti IP address.');
INSERT INTO public.quiz_questions (quiz_id, question_text, options, correct_answer, explanation) VALUES ((SELECT id FROM public.quizzes WHERE title = 'Computer Networking Quiz' LIMIT 1), 'Protokol transport layer yang reliable dan connection-oriented adalah?', '{"A": "UDP", "B": "TCP", "C": "IP", "D": "ICMP"}', 'B', 'TCP (Transmission Control Protocol) adalah protokol connection-oriented yang menjamin delivery data.');
INSERT INTO public.quiz_questions (quiz_id, question_text, options, correct_answer, explanation) VALUES ((SELECT id FROM public.quizzes WHERE title = 'Computer Networking Quiz' LIMIT 1), 'Perangkat jaringan yang menghubungkan perangkat dalam LAN adalah?', '{"A": "Router", "B": "Modem", "C": "Switch", "D": "Firewall"}', 'C', 'Switch menghubungkan perangkat dalam Local Area Network dan mengatur traffic berdasarkan MAC address.');
INSERT INTO public.quiz_questions (quiz_id, question_text, options, correct_answer, explanation) VALUES ((SELECT id FROM public.quizzes WHERE title = 'Computer Networking Quiz' LIMIT 1), 'Standar WiFi terbaru dengan kecepatan tinggi adalah?', '{"A": "802.11n", "B": "802.11ac", "C": "802.11ax", "D": "802.11g"}', 'C', '802.11ax (WiFi 6) adalah standar terbaru dengan kecepatan tinggi dan efisiensi energi yang lebih baik.');
INSERT INTO public.quiz_questions (quiz_id, question_text, options, correct_answer, explanation) VALUES ((SELECT id FROM public.quizzes WHERE title = 'Computer Networking Quiz' LIMIT 1), 'Teknik keamanan jaringan yang mengenkripsi data dalam transit adalah?', '{"A": "Firewall", "B": "VPN", "C": "Antivirus", "D": "Proxy"}', 'B', 'VPN (Virtual Private Network) mengenkripsi data dan membuat tunnel aman untuk transmisi data.');
INSERT INTO public.quiz_questions (quiz_id, question_text, options, correct_answer, explanation) VALUES ((SELECT id FROM public.quizzes WHERE title = 'Computer Networking Quiz' LIMIT 1), 'Command untuk mengecek konektivitas jaringan adalah?', '{"A": "ipconfig", "B": "ping", "C": "netstat", "D": "tracert"}', 'B', 'Ping digunakan untuk menguji konektivitas dan latency ke host tertentu.');
INSERT INTO public.quiz_questions (quiz_id, question_text, options, correct_answer, explanation) VALUES ((SELECT id FROM public.quizzes WHERE title = 'Computer Networking Quiz' LIMIT 1), 'Teknologi cloud networking yang memungkinkan isolasi jaringan virtual adalah?', '{"A": "CDN", "B": "VPC", "C": "Load Balancer", "D": "DNS"}', 'B', 'VPC (Virtual Private Cloud) memungkinkan pembuatan jaringan virtual terisolasi di cloud environment.');
INSERT INTO public.quiz_questions (quiz_id, question_text, options, correct_answer, explanation) VALUES ((SELECT id FROM public.quizzes WHERE title = 'Computer Networking Quiz' LIMIT 1), 'Protokol yang digunakan untuk mengirim email adalah?', '{"A": "HTTP", "B": "FTP", "C": "SMTP", "D": "DNS"}', 'C', 'SMTP (Simple Mail Transfer Protocol) adalah protokol standar untuk mengirim email melalui internet.');
INSERT INTO public.quiz_questions (quiz_id, question_text, options, correct_answer, explanation) VALUES ((SELECT id FROM public.quizzes WHERE title = 'Computer Networking Quiz' LIMIT 1), 'Teknologi yang memungkinkan multiple device terhubung ke internet melalui satu koneksi adalah?', '{"A": "Router", "B": "Switch", "C": "NAT", "D": "DHCP"}', 'C', 'NAT (Network Address Translation) memungkinkan multiple device menggunakan satu public IP address.');
INSERT INTO public.quiz_questions (quiz_id, question_text, options, correct_answer, explanation) VALUES ((SELECT id FROM public.quizzes WHERE title = 'Computer Networking Quiz' LIMIT 1), 'Sertifikasi fundamental networking dari CompTIA adalah?', '{"A": "CCNA", "B": "Network+", "C": "MCSE", "D": "RHCE"}', 'B', 'CompTIA Network+ adalah sertifikasi fundamental untuk networking yang diakui industri.');
INSERT INTO public.quiz_questions (quiz_id, question_text, options, correct_answer, explanation) VALUES ((SELECT id FROM public.quizzes WHERE title = 'Computer Networking Quiz' LIMIT 1), 'Teknologi yang menggunakan gelombang radio untuk komunikasi jarak jauh adalah?', '{"A": "Fiber Optic", "B": "Twisted Pair", "C": "Microwave", "D": "Coaxial"}', 'C', 'Microwave menggunakan gelombang radio untuk komunikasi point-to-point jarak jauh.');

-- Seed quiz questions for Telecommunications Quiz (TRANS)
INSERT INTO public.quiz_questions (quiz_id, question_text, options, correct_answer, explanation) VALUES ((SELECT id FROM public.quizzes WHERE title = 'Telecommunications Quiz' LIMIT 1), 'Apa yang dimaksud dengan telekomunikasi?', '{"A": "Komunikasi lokal", "B": "Transmisi informasi jarak jauh", "C": "Komunikasi tatap muka", "D": "Komunikasi tertulis"}', 'B', 'Telekomunikasi adalah teknologi yang memungkinkan transmisi informasi melalui jarak jauh menggunakan berbagai media.');
INSERT INTO public.quiz_questions (quiz_id, question_text, options, correct_answer, explanation) VALUES ((SELECT id FROM public.quizzes WHERE title = 'Telecommunications Quiz' LIMIT 1), 'Penemu telephone adalah?', '{"A": "Thomas Edison", "B": "Alexander Graham Bell", "C": "Nikola Tesla", "D": "Guglielmo Marconi"}', 'B', 'Alexander Graham Bell menemukan telephone pada tahun 1876.');
INSERT INTO public.quiz_questions (quiz_id, question_text, options, correct_answer, explanation) VALUES ((SELECT id FROM public.quizzes WHERE title = 'Telecommunications Quiz' LIMIT 1), 'Media transmisi dengan bandwidth tertinggi adalah?', '{"A": "Twisted Pair", "B": "Coaxial Cable", "C": "Fiber Optic", "D": "Wireless"}', 'C', 'Fiber optic memiliki bandwidth tertinggi dan kecepatan transmisi yang sangat tinggi.');
INSERT INTO public.quiz_questions (quiz_id, question_text, options, correct_answer, explanation) VALUES ((SELECT id FROM public.quizzes WHERE title = 'Telecommunications Quiz' LIMIT 1), 'Generasi jaringan seluler terkini adalah?', '{"A": "3G", "B": "4G LTE", "C": "5G", "D": "6G"}', 'C', '5G adalah generasi jaringan seluler terkini dengan kecepatan ultra-high dan latency rendah.');
INSERT INTO public.quiz_questions (quiz_id, question_text, options, correct_answer, explanation) VALUES ((SELECT id FROM public.quizzes WHERE title = 'Telecommunications Quiz' LIMIT 1), 'Teknik modulasi yang digunakan untuk radio AM adalah?', '{"A": "FM", "B": "PM", "C": "AM", "D": "FSK"}', 'C', 'AM (Amplitude Modulation) digunakan dalam radio AM dimana informasi dikodekan dalam amplitudo gelombang pembawa.');
INSERT INTO public.quiz_questions (quiz_id, question_text, options, correct_answer, explanation) VALUES ((SELECT id FROM public.quizzes WHERE title = 'Telecommunications Quiz' LIMIT 1), 'Satelit yang mengorbit pada ketinggian 36.000 km adalah?', '{"A": "LEO", "B": "MEO", "C": "GEO", "D": "HEO"}', 'C', 'GEO (Geostationary Earth Orbit) satelit mengorbit pada ketinggian 36.000 km dan terlihat stationary dari bumi.');
INSERT INTO public.quiz_questions (quiz_id, question_text, options, correct_answer, explanation) VALUES ((SELECT id FROM public.quizzes WHERE title = 'Telecommunications Quiz' LIMIT 1), 'Protokol yang digunakan untuk VoIP signaling adalah?', '{"A": "HTTP", "B": "SIP", "C": "SMTP", "D": "FTP"}', 'B', 'SIP (Session Initiation Protocol) adalah protokol signaling yang digunakan untuk menginisiasi, memelihara, dan mengakhiri sesi komunikasi real-time.');
INSERT INTO public.quiz_questions (quiz_id, question_text, options, correct_answer, explanation) VALUES ((SELECT id FROM public.quizzes WHERE title = 'Telecommunications Quiz' LIMIT 1), 'Teknologi wireless jarak dekat untuk device connectivity adalah?', '{"A": "WiFi", "B": "Bluetooth", "C": "NFC", "D": "GPS"}', 'B', 'Bluetooth adalah teknologi wireless untuk konektivitas jarak dekat antara device seperti headset, keyboard, dan smartphone.');
INSERT INTO public.quiz_questions (quiz_id, question_text, options, correct_answer, explanation) VALUES ((SELECT id FROM public.quizzes WHERE title = 'Telecommunications Quiz' LIMIT 1), 'Sistem telekomunikasi yang mengintegrasikan voice, data, dan video adalah?', '{"A": "PSTN", "B": "ISDN", "C": "VoIP", "D": "GSM"}', 'B', 'ISDN (Integrated Services Digital Network) mengintegrasikan berbagai jenis layanan telekomunikasi dalam satu jaringan digital.');
INSERT INTO public.quiz_questions (quiz_id, question_text, options, correct_answer, explanation) VALUES ((SELECT id FROM public.quizzes WHERE title = 'Telecommunications Quiz' LIMIT 1), 'Teknik multiplexing yang membagi waktu menjadi slot adalah?', '{"A": "FDM", "B": "TDM", "C": "CDMA", "D": "OFDM"}', 'B', 'TDM (Time Division Multiplexing) membagi waktu menjadi slot temporal untuk multiple sinyal.');
INSERT INTO public.quiz_questions (quiz_id, question_text, options, correct_answer, explanation) VALUES ((SELECT id FROM public.quizzes WHERE title = 'Telecommunications Quiz' LIMIT 1), 'Operator telekomunikasi terbesar di Indonesia adalah?', '{"A": "Indosat", "B": "XL", "C": "Telkom", "D": "Tri"}', 'C', 'Telkom adalah operator telekomunikasi terbesar di Indonesia dengan jaringan terluas.');
INSERT INTO public.quiz_questions (quiz_id, question_text, options, correct_answer, explanation) VALUES ((SELECT id FROM public.quizzes WHERE title = 'Telecommunications Quiz' LIMIT 1), 'Teknologi yang menggunakan cahaya untuk transmisi data adalah?', '{"A": "Radio", "B": "Microwave", "C": "Fiber Optic", "D": "Satellite"}', 'C', 'Fiber optic menggunakan cahaya untuk transmisi data dengan kecepatan tinggi dan jarak jauh.');
INSERT INTO public.quiz_questions (quiz_id, question_text, options, correct_answer, explanation) VALUES ((SELECT id FROM public.quizzes WHERE title = 'Telecommunications Quiz' LIMIT 1), 'Frekuensi yang digunakan untuk komunikasi seluler 5G adalah?', '{"A": "600 MHz", "B": "2.4 GHz", "C": "Sub-6 GHz dan mmWave", "D": "30 GHz"}', 'C', '5G menggunakan frekuensi sub-6 GHz untuk coverage luas dan mmWave (millimeter wave) untuk kecepatan tinggi.');
INSERT INTO public.quiz_questions (quiz_id, question_text, options, correct_answer, explanation) VALUES ((SELECT id FROM public.quizzes WHERE title = 'Telecommunications Quiz' LIMIT 1), 'Protokol internet yang menyediakan secure communication adalah?', '{"A": "HTTP", "B": "HTTPS", "C": "FTP", "D": "SMTP"}', 'B', 'HTTPS (HTTP Secure) menggunakan SSL/TLS untuk mengenkripsi komunikasi web.');
INSERT INTO public.quiz_questions (quiz_id, question_text, options, correct_answer, explanation) VALUES ((SELECT id FROM public.quizzes WHERE title = 'Telecommunications Quiz' LIMIT 1), 'Teknologi emerging yang menggunakan light untuk wireless communication adalah?', '{"A": "LiFi", "B": "WiFi", "C": "Bluetooth", "D": "NFC"}', 'A', 'LiFi (Light Fidelity) adalah teknologi wireless yang menggunakan cahaya LED untuk transmisi data.');

-- Seed quiz questions for Database Design Quiz (RPL)
INSERT INTO public.quiz_questions (quiz_id, question_text, options, correct_answer, explanation) VALUES ((SELECT id FROM public.quizzes WHERE title = 'Database Design Quiz' LIMIT 1), 'Apa yang dimaksud dengan database?', '{"A": "Program aplikasi", "B": "Kumpulan data terorganisir", "C": "Sistem operasi", "D": "Bahasa pemrograman"}', 'B', 'Database adalah kumpulan data yang terorganisir dan tersimpan secara sistematis untuk akses dan manipulasi yang mudah.');
INSERT INTO public.quiz_questions (quiz_id, question_text, options, correct_answer, explanation) VALUES ((SELECT id FROM public.quizzes WHERE title = 'Database Design Quiz' LIMIT 1), 'Model database relasional menggunakan konsep?', '{"A": "Hierarki", "B": "Tabel dan relasi", "C": "Objek", "D": "Dokumen"}', 'B', 'Database relasional menggunakan tabel (relations) dengan baris dan kolom, dan relasi antar tabel.');
INSERT INTO public.quiz_questions (quiz_id, question_text, options, correct_answer, explanation) VALUES ((SELECT id FROM public.quizzes WHERE title = 'Database Design Quiz' LIMIT 1), 'Bahasa query standar untuk database relasional adalah?', '{"A": "HTML", "B": "CSS", "C": "SQL", "D": "JavaScript"}', 'C', 'SQL (Structured Query Language) adalah bahasa standar untuk mengelola dan memanipulasi database relasional.');
INSERT INTO public.quiz_questions (quiz_id, question_text, options, correct_answer, explanation) VALUES ((SELECT id FROM public.quizzes WHERE title = 'Database Design Quiz' LIMIT 1), 'Kunci utama (primary key) dalam tabel berfungsi untuk?', '{"A": "Mengenkripsi data", "B": "Mengidentifikasi unik setiap record", "C": "Menyimpan data besar", "D": "Membuat backup"}', 'B', 'Primary key secara unik mengidentifikasi setiap record dalam tabel dan tidak boleh duplikat.');
INSERT INTO public.quiz_questions (quiz_id, question_text, options, correct_answer, explanation) VALUES ((SELECT id FROM public.quizzes WHERE title = 'Database Design Quiz' LIMIT 1), 'Normalisasi database bertujuan untuk?', '{"A": "Mempercepat query", "B": "Mengurangi redundansi data", "C": "Meningkatkan security", "D": "Memperbesar storage"}', 'B', 'Normalisasi bertujuan mengurangi redundansi data dan meningkatkan integritas data dalam database.');
INSERT INTO public.quiz_questions (quiz_id, question_text, options, correct_answer, explanation) VALUES ((SELECT id FROM public.quizzes WHERE title = 'Database Design Quiz' LIMIT 1), 'Jenis relasi many-to-many dalam ER diagram ditandai dengan?', '{"A": "Garis lurus", "B": "Simbol crow''s foot", "C": "Lingkaran", "D": "Kotak"}', 'B', 'Crow''s foot notation digunakan untuk menunjukkan relasi many-to-many dalam Entity Relationship diagram.');
INSERT INTO public.quiz_questions (quiz_id, question_text, options, correct_answer, explanation) VALUES ((SELECT id FROM public.quizzes WHERE title = 'Database Design Quiz' LIMIT 1), 'Perintah SQL untuk mengambil data dari tabel adalah?', '{"A": "INSERT", "B": "UPDATE", "C": "SELECT", "D": "DELETE"}', 'C', 'SELECT digunakan untuk mengambil/query data dari satu atau lebih tabel dalam database.');
INSERT INTO public.quiz_questions (quiz_id, question_text, options, correct_answer, explanation) VALUES ((SELECT id FROM public.quizzes WHERE title = 'Database Design Quiz' LIMIT 1), 'Konsep ACID dalam database management system meliputi?', '{"A": "Atomicity, Consistency, Isolation, Durability", "B": "Access, Control, Integrity, Data", "C": "Application, Connection, Interface, Database", "D": "Array, Class, Instance, Definition"}', 'A', 'ACID adalah properti yang menjamin keandalan transaksi database: Atomicity, Consistency, Isolation, Durability.');
INSERT INTO public.quiz_questions (quiz_id, question_text, options, correct_answer, explanation) VALUES ((SELECT id FROM public.quizzes WHERE title = 'Database Design Quiz' LIMIT 1), 'Database NoSQL cocok digunakan untuk data yang?', '{"A": "Terstruktur dan relasional", "B": "Besar, tidak terstruktur, real-time", "C": "Kecil dan sederhana", "D": "Statis dan jarang berubah"}', 'B', 'NoSQL database dirancang untuk menangani big data, data tidak terstruktur, dan aplikasi real-time.');
INSERT INTO public.quiz_questions (quiz_id, question_text, options, correct_answer, explanation) VALUES ((SELECT id FROM public.quizzes WHERE title = 'Database Design Quiz' LIMIT 1), 'Index dalam database berfungsi untuk?', '{"A": "Mengenkripsi data", "B": "Mempercepat pencarian data", "C": "Menyimpan backup", "D": "Mengkompres data"}', 'B', 'Index adalah struktur data yang mempercepat operasi pencarian dan query pada kolom tertentu.');
INSERT INTO public.quiz_questions (quiz_id, question_text, options, correct_answer, explanation) VALUES ((SELECT id FROM public.quizzes WHERE title = 'Database Design Quiz' LIMIT 1), 'Foreign key dalam tabel relasional mereferensi?', '{"A": "Primary key tabel lain", "B": "Data eksternal", "C": "File sistem", "D": "Memory cache"}', 'A', 'Foreign key adalah kolom yang mereferensi primary key dari tabel lain untuk membuat relasi.');
INSERT INTO public.quiz_questions (quiz_id, question_text, options, correct_answer, explanation) VALUES ((SELECT id FROM public.quizzes WHERE title = 'Database Design Quiz' LIMIT 1), 'Perintah SQL untuk menambahkan data baru ke tabel adalah?', '{"A": "SELECT", "B": "INSERT", "C": "UPDATE", "D": "CREATE"}', 'B', 'INSERT digunakan untuk menambahkan record/baris data baru ke dalam tabel.');
INSERT INTO public.quiz_questions (quiz_id, question_text, options, correct_answer, explanation) VALUES ((SELECT id FROM public.quizzes WHERE title = 'Database Design Quiz' LIMIT 1), 'Database management system populer open source adalah?', '{"A": "Oracle", "B": "SQL Server", "C": "MySQL", "D": "DB2"}', 'C', 'MySQL adalah DBMS open source yang paling populer dan banyak digunakan untuk aplikasi web.');
INSERT INTO public.quiz_questions (quiz_id, question_text, options, correct_answer, explanation) VALUES ((SELECT id FROM public.quizzes WHERE title = 'Database Design Quiz' LIMIT 1), 'Konsep denormalisasi dalam database design digunakan untuk?', '{"A": "Mengurangi redundansi", "B": "Mempercepat query read", "C": "Menghemat storage", "D": "Meningkatkan security"}', 'B', 'Denormalisasi menambahkan redundansi data untuk mempercepat operasi read pada database yang sering diakses.');

-- Additional quizzes for DKV
INSERT INTO public.quizzes (title, description, total_questions, passing_score, category)
SELECT 'Graphic Design Tools Quiz', 'Test your knowledge of graphic design software and tools', 4, 80, 'DKV'
WHERE NOT EXISTS (SELECT 1 FROM public.quizzes WHERE title = 'Graphic Design Tools Quiz');

INSERT INTO public.quizzes (title, description, total_questions, passing_score, category)
SELECT 'Color Theory Quiz', 'Test your understanding of color principles in design', 4, 80, 'DKV'
WHERE NOT EXISTS (SELECT 1 FROM public.quizzes WHERE title = 'Color Theory Quiz');

INSERT INTO public.quizzes (title, description, total_questions, passing_score, category)
SELECT 'Typography Quiz', 'Test your typography and font design knowledge', 4, 80, 'DKV'
WHERE NOT EXISTS (SELECT 1 FROM public.quizzes WHERE title = 'Typography Quiz');

-- Additional quizzes for TKJ
INSERT INTO public.quizzes (title, description, total_questions, passing_score, category)
SELECT 'Network Security Quiz', 'Test your network security knowledge', 4, 80, 'TKJ'
WHERE NOT EXISTS (SELECT 1 FROM public.quizzes WHERE title = 'Network Security Quiz');

INSERT INTO public.quizzes (title, description, total_questions, passing_score, category)
SELECT 'Wireless Networking Quiz', 'Test your wireless networking knowledge', 4, 80, 'TKJ'
WHERE NOT EXISTS (SELECT 1 FROM public.quizzes WHERE title = 'Wireless Networking Quiz');

INSERT INTO public.quizzes (title, description, total_questions, passing_score, category)
SELECT 'Network Protocols Quiz', 'Test your knowledge of network protocols', 4, 80, 'TKJ'
WHERE NOT EXISTS (SELECT 1 FROM public.quizzes WHERE title = 'Network Protocols Quiz');

-- Additional quizzes for TRANS
INSERT INTO public.quizzes (title, description, total_questions, passing_score, category)
SELECT 'Mobile Communications Quiz', 'Test your mobile communications knowledge', 4, 80, 'TRANS'
WHERE NOT EXISTS (SELECT 1 FROM public.quizzes WHERE title = 'Mobile Communications Quiz');

INSERT INTO public.quizzes (title, description, total_questions, passing_score, category)
SELECT 'Satellite Communications Quiz', 'Test your satellite communications knowledge', 4, 80, 'TRANS'
WHERE NOT EXISTS (SELECT 1 FROM public.quizzes WHERE title = 'Satellite Communications Quiz');

INSERT INTO public.quizzes (title, description, total_questions, passing_score, category)
SELECT 'Internet Technologies Quiz', 'Test your internet technologies knowledge', 4, 80, 'TRANS'
WHERE NOT EXISTS (SELECT 1 FROM public.quizzes WHERE title = 'Internet Technologies Quiz');

-- Additional quizzes for RPL
INSERT INTO public.quizzes (title, description, total_questions, passing_score, category)
SELECT 'SQL Fundamentals Quiz', 'Test your SQL fundamentals knowledge', 4, 80, 'RPL'
WHERE NOT EXISTS (SELECT 1 FROM public.quizzes WHERE title = 'SQL Fundamentals Quiz');

INSERT INTO public.quizzes (title, description, total_questions, passing_score, category)
SELECT 'NoSQL Databases Quiz', 'Test your NoSQL databases knowledge', 4, 80, 'RPL'
WHERE NOT EXISTS (SELECT 1 FROM public.quizzes WHERE title = 'NoSQL Databases Quiz');

INSERT INTO public.quizzes (title, description, total_questions, passing_score, category)
SELECT 'Database Security Quiz', 'Test your database security knowledge', 4, 80, 'RPL'
WHERE NOT EXISTS (SELECT 1 FROM public.quizzes WHERE title = 'Database Security Quiz');

-- Questions for Graphic Design Tools Quiz (DKV)
INSERT INTO public.quiz_questions (quiz_id, question_text, options, correct_answer, explanation) VALUES ((SELECT id FROM public.quizzes WHERE title = 'Graphic Design Tools Quiz' LIMIT 1), 'Software yang digunakan untuk vektor graphics adalah?', '{"A": "Adobe Photoshop", "B": "Adobe Illustrator", "C": "Adobe InDesign", "D": "CorelDRAW"}', 'B', 'Adobe Illustrator adalah software utama untuk desain vektor.');
INSERT INTO public.quiz_questions (quiz_id, question_text, options, correct_answer, explanation) VALUES ((SELECT id FROM public.quizzes WHERE title = 'Graphic Design Tools Quiz' LIMIT 1), 'Tool di Photoshop untuk memilih area berbentuk persegi panjang adalah?', '{"A": "Lasso Tool", "B": "Magic Wand", "C": "Rectangular Marquee", "D": "Brush Tool"}', 'C', 'Rectangular Marquee Tool digunakan untuk memilih area persegi panjang.');
INSERT INTO public.quiz_questions (quiz_id, question_text, options, correct_answer, explanation) VALUES ((SELECT id FROM public.quizzes WHERE title = 'Graphic Design Tools Quiz' LIMIT 1), 'Software yang digunakan untuk layout dan publishing adalah?', '{"A": "Adobe Photoshop", "B": "Adobe Illustrator", "C": "Adobe InDesign", "D": "Adobe Premiere"}', 'C', 'Adobe InDesign adalah software untuk layout dan publishing.');
INSERT INTO public.quiz_questions (quiz_id, question_text, options, correct_answer, explanation) VALUES ((SELECT id FROM public.quizzes WHERE title = 'Graphic Design Tools Quiz' LIMIT 1), 'Tool di Illustrator untuk membuat bentuk dasar seperti lingkaran adalah?', '{"A": "Pen Tool", "B": "Shape Builder", "C": "Ellipse Tool", "D": "Type Tool"}', 'C', 'Ellipse Tool digunakan untuk membuat bentuk oval dan lingkaran.');

-- Questions for Color Theory Quiz (DKV)
INSERT INTO public.quiz_questions (quiz_id, question_text, options, correct_answer, explanation) VALUES ((SELECT id FROM public.quizzes WHERE title = 'Color Theory Quiz' LIMIT 1), 'Warna yang dihasilkan dari campuran merah dan kuning adalah?', '{"A": "Hijau", "B": "Orange", "C": "Ungu", "D": "Biru"}', 'B', 'Merah + Kuning = Orange dalam teori warna.');
INSERT INTO public.quiz_questions (quiz_id, question_text, options, correct_answer, explanation) VALUES ((SELECT id FROM public.quizzes WHERE title = 'Color Theory Quiz' LIMIT 1), 'Kontras warna yang memberikan kesan tenang adalah?', '{"A": "Merah vs Hijau", "B": "Biru vs Orange", "C": "Biru vs Hijau", "D": "Merah vs Kuning"}', 'C', 'Biru dan hijau adalah warna analog yang memberikan kesan harmonis.');
INSERT INTO public.quiz_questions (quiz_id, question_text, options, correct_answer, explanation) VALUES ((SELECT id FROM public.quizzes WHERE title = 'Color Theory Quiz' LIMIT 1), 'Warna primer dalam model RGB adalah?', '{"A": "Merah, Kuning, Biru", "B": "Merah, Hijau, Biru", "C": "Cyan, Magenta, Yellow", "D": "Hitam, Putih, Abu"}', 'B', 'RGB menggunakan Merah, Hijau, Biru sebagai warna primer.');
INSERT INTO public.quiz_questions (quiz_id, question_text, options, correct_answer, explanation) VALUES ((SELECT id FROM public.quizzes WHERE title = 'Color Theory Quiz' LIMIT 1), 'Prinsip warna yang menunjukkan keseimbangan adalah?', '{"A": "Hue", "B": "Saturation", "C": "Value", "D": "Balance"}', 'D', 'Balance dalam warna menciptakan harmoni visual.');

-- Questions for Typography Quiz (DKV)
INSERT INTO public.quiz_questions (quiz_id, question_text, options, correct_answer, explanation) VALUES ((SELECT id FROM public.quizzes WHERE title = 'Typography Quiz' LIMIT 1), 'Jenis font yang memiliki kaki pada huruf adalah?', '{"A": "Sans-serif", "B": "Serif", "C": "Script", "D": "Display"}', 'B', 'Serif fonts memiliki kaki atau stroke tambahan pada huruf.');
INSERT INTO public.quiz_questions (quiz_id, question_text, options, correct_answer, explanation) VALUES ((SELECT id FROM public.quizzes WHERE title = 'Typography Quiz' LIMIT 1), 'Spacing antara karakter dalam typography disebut?', '{"A": "Kerning", "B": "Leading", "C": "Tracking", "D": "Alignment"}', 'C', 'Tracking adalah spacing keseluruhan antara karakter.');
INSERT INTO public.quiz_questions (quiz_id, question_text, options, correct_answer, explanation) VALUES ((SELECT id FROM public.quizzes WHERE title = 'Typography Quiz' LIMIT 1), 'Font family yang mudah dibaca untuk body text adalah?', '{"A": "Arial", "B": "Times New Roman", "C": "Comic Sans", "D": "Impact"}', 'B', 'Times New Roman adalah serif font yang readable untuk body text.');
INSERT INTO public.quiz_questions (quiz_id, question_text, options, correct_answer, explanation) VALUES ((SELECT id FROM public.quizzes WHERE title = 'Typography Quiz' LIMIT 1), 'Ukuran font yang standar untuk heading adalah?', '{"A": "8-10 pt", "B": "12-14 pt", "C": "18-24 pt", "D": "36-48 pt"}', 'C', '18-24 pt cocok untuk heading agar menonjol.');

-- Questions for Network Security Quiz (TKJ)
INSERT INTO public.quiz_questions (quiz_id, question_text, options, correct_answer, explanation) VALUES ((SELECT id FROM public.quizzes WHERE title = 'Network Security Quiz' LIMIT 1), 'Teknik keamanan yang mengubah data menjadi kode tidak dapat dibaca adalah?', '{"A": "Firewall", "B": "Encryption", "C": "Antivirus", "D": "Backup"}', 'B', 'Encryption mengubah data menjadi format yang tidak dapat dibaca tanpa kunci.');
INSERT INTO public.quiz_questions (quiz_id, question_text, options, correct_answer, explanation) VALUES ((SELECT id FROM public.quizzes WHERE title = 'Network Security Quiz' LIMIT 1), 'Perangkat yang memfilter traffic jaringan berdasarkan aturan adalah?', '{"A": "Router", "B": "Switch", "C": "Firewall", "D": "Modem"}', 'C', 'Firewall memfilter traffic masuk dan keluar berdasarkan aturan keamanan.');
INSERT INTO public.quiz_questions (quiz_id, question_text, options, correct_answer, explanation) VALUES ((SELECT id FROM public.quizzes WHERE title = 'Network Security Quiz' LIMIT 1), 'Serangan dimana penyerang menyamar sebagai entitas tepercaya adalah?', '{"A": "Virus", "B": "Phishing", "C": "Spoofing", "D": "Malware"}', 'C', 'Spoofing adalah teknik dimana penyerang menyamar sebagai host yang sah.');
INSERT INTO public.quiz_questions (quiz_id, question_text, options, correct_answer, explanation) VALUES ((SELECT id FROM public.quizzes WHERE title = 'Network Security Quiz' LIMIT 1), 'Protokol yang menyediakan secure communication melalui internet adalah?', '{"A": "HTTP", "B": "HTTPS", "C": "FTP", "D": "SMTP"}', 'B', 'HTTPS menggunakan SSL/TLS untuk secure communication.');

-- Questions for Wireless Networking Quiz (TKJ)
INSERT INTO public.quiz_questions (quiz_id, question_text, options, correct_answer, explanation) VALUES ((SELECT id FROM public.quizzes WHERE title = 'Wireless Networking Quiz' LIMIT 1), 'Standar WiFi yang mendukung kecepatan hingga 54 Mbps adalah?', '{"A": "802.11a", "B": "802.11b", "C": "802.11g", "D": "802.11n"}', 'C', '802.11g mendukung kecepatan hingga 54 Mbps.');
INSERT INTO public.quiz_questions (quiz_id, question_text, options, correct_answer, explanation) VALUES ((SELECT id FROM public.quizzes WHERE title = 'Wireless Networking Quiz' LIMIT 1), 'Frekuensi yang digunakan oleh WiFi 2.4 GHz adalah?', '{"A": "2.4 GHz", "B": "5 GHz", "C": "2.4 dan 5 GHz", "D": "6 GHz"}', 'A', 'WiFi 2.4 GHz menggunakan frekuensi 2.4 GHz.');
INSERT INTO public.quiz_questions (quiz_id, question_text, options, correct_answer, explanation) VALUES ((SELECT id FROM public.quizzes WHERE title = 'Wireless Networking Quiz' LIMIT 1), 'Teknologi wireless untuk koneksi jarak dekat adalah?', '{"A": "WiFi", "B": "Bluetooth", "C": "NFC", "D": "GPS"}', 'B', 'Bluetooth digunakan untuk koneksi wireless jarak dekat.');
INSERT INTO public.quiz_questions (quiz_id, question_text, options, correct_answer, explanation) VALUES ((SELECT id FROM public.quizzes WHERE title = 'Wireless Networking Quiz' LIMIT 1), 'Keuntungan menggunakan 5 GHz dibanding 2.4 GHz adalah?', '{"A": "Jangkauan lebih luas", "B": "Kecepatan lebih tinggi", "C": "Kompatibilitas lebih baik", "D": "Biaya lebih murah"}', 'B', '5 GHz menawarkan kecepatan lebih tinggi meskipun jangkauan lebih terbatas.');

-- Questions for Network Protocols Quiz (TKJ)
INSERT INTO public.quiz_questions (quiz_id, question_text, options, correct_answer, explanation) VALUES ((SELECT id FROM public.quizzes WHERE title = 'Network Protocols Quiz' LIMIT 1), 'Protokol yang digunakan untuk mengirim email adalah?', '{"A": "HTTP", "B": "FTP", "C": "SMTP", "D": "DNS"}', 'C', 'SMTP digunakan untuk mengirim email.');
INSERT INTO public.quiz_questions (quiz_id, question_text, options, correct_answer, explanation) VALUES ((SELECT id FROM public.quizzes WHERE title = 'Network Protocols Quiz' LIMIT 1), 'Protokol yang mentranslasikan domain name ke IP address adalah?', '{"A": "HTTP", "B": "FTP", "C": "SMTP", "D": "DNS"}', 'D', 'DNS mentranslasikan nama domain ke alamat IP.');
INSERT INTO public.quiz_questions (quiz_id, question_text, options, correct_answer, explanation) VALUES ((SELECT id FROM public.quizzes WHERE title = 'Network Protocols Quiz' LIMIT 1), 'Protokol transport layer yang connection-oriented adalah?', '{"A": "UDP", "B": "TCP", "C": "IP", "D": "ICMP"}', 'B', 'TCP adalah connection-oriented protocol.');
INSERT INTO public.quiz_questions (quiz_id, question_text, options, correct_answer, explanation) VALUES ((SELECT id FROM public.quizzes WHERE title = 'Network Protocols Quiz' LIMIT 1), 'Protokol yang digunakan untuk file transfer adalah?', '{"A": "HTTP", "B": "FTP", "C": "SMTP", "D": "DNS"}', 'B', 'FTP digunakan untuk transfer file.');

-- Questions for Mobile Communications Quiz (TRANS)
INSERT INTO public.quiz_questions (quiz_id, question_text, options, correct_answer, explanation) VALUES ((SELECT id FROM public.quizzes WHERE title = 'Mobile Communications Quiz' LIMIT 1), 'Generasi jaringan seluler yang pertama kali memperkenalkan data digital adalah?', '{"A": "1G", "B": "2G", "C": "3G", "D": "4G"}', 'B', '2G memperkenalkan layanan data digital.');
INSERT INTO public.quiz_questions (quiz_id, question_text, options, correct_answer, explanation) VALUES ((SELECT id FROM public.quizzes WHERE title = 'Mobile Communications Quiz' LIMIT 1), 'Teknologi yang digunakan dalam 4G LTE adalah?', '{"A": "GSM", "B": "CDMA", "C": "OFDM", "D": "FDMA"}', 'C', 'LTE menggunakan OFDM untuk modulasi.');
INSERT INTO public.quiz_questions (quiz_id, question_text, options, correct_answer, explanation) VALUES ((SELECT id FROM public.quizzes WHERE title = 'Mobile Communications Quiz' LIMIT 1), 'Frekuensi yang digunakan untuk komunikasi seluler adalah?', '{"A": "VHF", "B": "UHF", "C": "SHF", "D": "EHF"}', 'B', 'Komunikasi seluler menggunakan UHF band.');
INSERT INTO public.quiz_questions (quiz_id, question_text, options, correct_answer, explanation) VALUES ((SELECT id FROM public.quizzes WHERE title = 'Mobile Communications Quiz' LIMIT 1), 'Sistem yang mengatur komunikasi seluler di Indonesia adalah?', '{"A": "GSM", "B": "CDMA", "C": "LTE", "D": "Semua benar"}', 'D', 'Indonesia menggunakan GSM, CDMA, dan LTE.');

-- Questions for Satellite Communications Quiz (TRANS)
INSERT INTO public.quiz_questions (quiz_id, question_text, options, correct_answer, explanation) VALUES ((SELECT id FROM public.quizzes WHERE title = 'Satellite Communications Quiz' LIMIT 1), 'Satelit yang mengorbit pada ketinggian 36.000 km adalah?', '{"A": "LEO", "B": "MEO", "C": "GEO", "D": "HEO"}', 'C', 'GEO satelit mengorbit pada 36.000 km.');
INSERT INTO public.quiz_questions (quiz_id, question_text, options, correct_answer, explanation) VALUES ((SELECT id FROM public.quizzes WHERE title = 'Satellite Communications Quiz' LIMIT 1), 'Keuntungan komunikasi satelit adalah?', '{"A": "Biaya rendah", "B": "Coverage global", "C": "Kecepatan tinggi", "D": "Latency rendah"}', 'B', 'Satelit memberikan coverage global.');
INSERT INTO public.quiz_questions (quiz_id, question_text, options, correct_answer, explanation) VALUES ((SELECT id FROM public.quizzes WHERE title = 'Satellite Communications Quiz' LIMIT 1), 'Frekuensi yang digunakan untuk komunikasi satelit adalah?', '{"A": "HF", "B": "VHF", "C": "UHF", "D": "Ku band"}', 'D', 'Ku band umum digunakan untuk satelit komunikasi.');
INSERT INTO public.quiz_questions (quiz_id, question_text, options, correct_answer, explanation) VALUES ((SELECT id FROM public.quizzes WHERE title = 'Satellite Communications Quiz' LIMIT 1), 'Sistem navigasi satelit global adalah?', '{"A": "GPS", "B": "GLONASS", "C": "Galileo", "D": "Semua benar"}', 'D', 'GPS, GLONASS, Galileo adalah sistem GNSS.');

-- Questions for Internet Technologies Quiz (TRANS)
INSERT INTO public.quiz_questions (quiz_id, question_text, options, correct_answer, explanation) VALUES ((SELECT id FROM public.quizzes WHERE title = 'Internet Technologies Quiz' LIMIT 1), 'Protokol yang digunakan untuk web browsing adalah?', '{"A": "FTP", "B": "SMTP", "C": "HTTP", "D": "DNS"}', 'C', 'HTTP digunakan untuk web browsing.');
INSERT INTO public.quiz_questions (quiz_id, question_text, options, correct_answer, explanation) VALUES ((SELECT id FROM public.quizzes WHERE title = 'Internet Technologies Quiz' LIMIT 1), 'Teknologi yang mempercepat loading web dengan caching adalah?', '{"A": "DNS", "B": "CDN", "C": "VPN", "D": "Proxy"}', 'B', 'CDN menggunakan caching untuk mempercepat delivery konten.');
INSERT INTO public.quiz_questions (quiz_id, question_text, options, correct_answer, explanation) VALUES ((SELECT id FROM public.quizzes WHERE title = 'Internet Technologies Quiz' LIMIT 1), 'Protokol secure untuk web adalah?', '{"A": "HTTP", "B": "HTTPS", "C": "FTP", "D": "SMTP"}', 'B', 'HTTPS menyediakan secure communication.');
INSERT INTO public.quiz_questions (quiz_id, question_text, options, correct_answer, explanation) VALUES ((SELECT id FROM public.quizzes WHERE title = 'Internet Technologies Quiz' LIMIT 1), 'Teknologi yang memungkinkan video streaming real-time adalah?', '{"A": "HTTP", "B": "RTMP", "C": "WebRTC", "D": "SMTP"}', 'C', 'WebRTC memungkinkan real-time communication termasuk video.');

-- Questions for SQL Fundamentals Quiz (RPL)
INSERT INTO public.quiz_questions (quiz_id, question_text, options, correct_answer, explanation) VALUES ((SELECT id FROM public.quizzes WHERE title = 'SQL Fundamentals Quiz' LIMIT 1), 'Perintah SQL untuk membuat tabel baru adalah?', '{"A": "INSERT", "B": "UPDATE", "C": "CREATE", "D": "SELECT"}', 'C', 'CREATE TABLE digunakan untuk membuat tabel baru.');
INSERT INTO public.quiz_questions (quiz_id, question_text, options, correct_answer, explanation) VALUES ((SELECT id FROM public.quizzes WHERE title = 'SQL Fundamentals Quiz' LIMIT 1), 'Kata kunci untuk mengambil data unik adalah?', '{"A": "DISTINCT", "B": "UNIQUE", "C": "GROUP BY", "D": "ORDER BY"}', 'A', 'DISTINCT mengembalikan nilai unik.');
INSERT INTO public.quiz_questions (quiz_id, question_text, options, correct_answer, explanation) VALUES ((SELECT id FROM public.quizzes WHERE title = 'SQL Fundamentals Quiz' LIMIT 1), 'Operator untuk mencari nilai dalam range adalah?', '{"A": "IN", "B": "BETWEEN", "C": "LIKE", "D": "EXISTS"}', 'B', 'BETWEEN digunakan untuk range.');
INSERT INTO public.quiz_questions (quiz_id, question_text, options, correct_answer, explanation) VALUES ((SELECT id FROM public.quizzes WHERE title = 'SQL Fundamentals Quiz' LIMIT 1), 'Fungsi agregat untuk menghitung jumlah record adalah?', '{"A": "SUM", "B": "AVG", "C": "COUNT", "D": "MAX"}', 'C', 'COUNT menghitung jumlah record.');

-- Questions for NoSQL Databases Quiz (RPL)
INSERT INTO public.quiz_questions (quiz_id, question_text, options, correct_answer, explanation) VALUES ((SELECT id FROM public.quizzes WHERE title = 'NoSQL Databases Quiz' LIMIT 1), 'Jenis NoSQL database yang menyimpan data sebagai dokumen adalah?', '{"A": "Key-Value", "B": "Document", "C": "Column-Family", "D": "Graph"}', 'B', 'Document database seperti MongoDB menyimpan data sebagai dokumen JSON.');
INSERT INTO public.quiz_questions (quiz_id, question_text, options, correct_answer, explanation) VALUES ((SELECT id FROM public.quizzes WHERE title = 'NoSQL Databases Quiz' LIMIT 1), 'Keuntungan NoSQL dibanding SQL adalah?', '{"A": "Schema fixed", "B": "Scalability horizontal", "C": "ACID compliance", "D": "Complex queries"}', 'B', 'NoSQL lebih mudah di-scale horizontal.');
INSERT INTO public.quiz_questions (quiz_id, question_text, options, correct_answer, explanation) VALUES ((SELECT id FROM public.quizzes WHERE title = 'NoSQL Databases Quiz' LIMIT 1), 'Database NoSQL populer untuk big data adalah?', '{"A": "MySQL", "B": "PostgreSQL", "C": "MongoDB", "D": "Oracle"}', 'C', 'MongoDB adalah NoSQL database populer.');
INSERT INTO public.quiz_questions (quiz_id, question_text, options, correct_answer, explanation) VALUES ((SELECT id FROM public.quizzes WHERE title = 'NoSQL Databases Quiz' LIMIT 1), 'NoSQL database yang menggunakan graph structure adalah?', '{"A": "Redis", "B": "Cassandra", "C": "Neo4j", "D": "CouchDB"}', 'C', 'Neo4j adalah graph database.');

-- Questions for Database Security Quiz (RPL)
INSERT INTO public.quiz_questions (quiz_id, question_text, options, correct_answer, explanation) VALUES ((SELECT id FROM public.quizzes WHERE title = 'Database Security Quiz' LIMIT 1), 'Teknik untuk melindungi data sensitif adalah?', '{"A": "Encryption", "B": "Compression", "C": "Backup", "D": "Indexing"}', 'A', 'Encryption melindungi data dari akses tidak sah.');
INSERT INTO public.quiz_questions (quiz_id, question_text, options, correct_answer, explanation) VALUES ((SELECT id FROM public.quizzes WHERE title = 'Database Security Quiz' LIMIT 1), 'Serangan dimana penyerang mencoba kombinasi password adalah?', '{"A": "Phishing", "B": "Brute Force", "C": "SQL Injection", "D": "XSS"}', 'B', 'Brute force mencoba semua kombinasi password.');
INSERT INTO public.quiz_questions (quiz_id, question_text, options, correct_answer, explanation) VALUES ((SELECT id FROM public.quizzes WHERE title = 'Database Security Quiz' LIMIT 1), 'Mekanisme untuk mengontrol akses ke database adalah?', '{"A": "Authentication", "B": "Authorization", "C": "Auditing", "D": "Semua benar"}', 'D', 'Authentication, authorization, auditing penting untuk security.');
INSERT INTO public.quiz_questions (quiz_id, question_text, options, correct_answer, explanation) VALUES ((SELECT id FROM public.quizzes WHERE title = 'Database Security Quiz' LIMIT 1), 'Teknik untuk mencegah SQL injection adalah?', '{"A": "Input validation", "B": "Prepared statements", "C": "Firewall", "D": "Encryption"}', 'B', 'Prepared statements mencegah SQL injection.');
